<?php
add_action( 'init', 'protax_register_case_studies_post_type' );
function protax_register_case_studies_post_type() {
	$labels = [
		'name'                     => esc_html__( 'Case Studies', 'protax' ),
		'singular_name'            => esc_html__( 'Case Study', 'protax' ),
		'add_new'                  => esc_html__( 'Add New', 'protax' ),
		'add_new_item'             => esc_html__( 'Add New Case Study', 'protax' ),
		'edit_item'                => esc_html__( 'Edit Case Study', 'protax' ),
		'new_item'                 => esc_html__( 'New Case Study', 'protax' ),
		'view_item'                => esc_html__( 'View Case Study', 'protax' ),
		'view_items'               => esc_html__( 'View Case Studies', 'protax' ),
		'search_items'             => esc_html__( 'Search Case Studies', 'protax' ),
		'not_found'                => esc_html__( 'No case studies found.', 'protax' ),
		'not_found_in_trash'       => esc_html__( 'No case studies found in Trash.', 'protax' ),
		'parent_item_colon'        => esc_html__( 'Parent Case Study:', 'protax' ),
		'all_items'                => esc_html__( 'All Case Studies', 'protax' ),
		'archives'                 => esc_html__( 'Case Study Archives', 'protax' ),
		'attributes'               => esc_html__( 'Case Study Attributes', 'protax' ),
		'insert_into_item'         => esc_html__( 'Insert into case study', 'protax' ),
		'uploaded_to_this_item'    => esc_html__( 'Uploaded to this case study', 'protax' ),
		'featured_image'           => esc_html__( 'Featured image', 'protax' ),
		'set_featured_image'       => esc_html__( 'Set featured image', 'protax' ),
		'remove_featured_image'    => esc_html__( 'Remove featured image', 'protax' ),
		'use_featured_image'       => esc_html__( 'Use as featured image', 'protax' ),
		'menu_name'                => esc_html__( 'Case Studies', 'protax' ),
		'filter_items_list'        => esc_html__( 'Filter case studies list', 'protax' ),
		'filter_by_date'           => esc_html__( '', 'protax' ),
		'items_list_navigation'    => esc_html__( 'Case Studies list navigation', 'protax' ),
		'items_list'               => esc_html__( 'Case Studies list', 'protax' ),
		'item_published'           => esc_html__( 'Case Study published.', 'protax' ),
		'item_published_privately' => esc_html__( 'Case Study published privately.', 'protax' ),
		'item_reverted_to_draft'   => esc_html__( 'Case Study reverted to draft.', 'protax' ),
		'item_scheduled'           => esc_html__( 'Case Study scheduled.', 'protax' ),
		'item_updated'             => esc_html__( 'Case Study updated.', 'protax' ),
		'text_domain'              => esc_html__( 'protax', 'protax' ),
	];
	$args = [
		'label'               => esc_html__( 'Case Studies', 'protax' ),
		'labels'              => $labels,
		'description'         => '',
		'public'              => true,
		'hierarchical'        => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'show_in_rest'        => true,
		'query_var'           => true,
		'can_export'          => true,
		'delete_with_user'    => true,
		'order'               => true,
		'has_archive'         => true,
		'rest_base'           => '',
		'show_in_menu'        => true,
		'menu_position'       => 6,
		'menu_icon'           => 'fa-solid fa-building-user',
		'capability_type'     => 'page',
		'supports'            => ['title', 'editor', 'custom-fields', 'revisions', 'page-attributes', 'thumbnail', 'excerpt'],
		'taxonomies'          => ['case-study-type', 'case-study-timeline', 'case-study-county'],
		'rewrite'             => [
			'with_front' => true,
		],
	];

	register_post_type( 'case-study', $args );
}

add_action( 'init', 'protax_register_team_members' );
function protax_register_team_members() {
	$labels = [
		'name'                     => esc_html__( 'Team Members', 'protaxllc' ),
		'singular_name'            => esc_html__( 'Team Member', 'protaxllc' ),
		'add_new'                  => esc_html__( 'Add New', 'protaxllc' ),
		'add_new_item'             => esc_html__( 'Add New Team Member', 'protaxllc' ),
		'edit_item'                => esc_html__( 'Edit Team Member', 'protaxllc' ),
		'new_item'                 => esc_html__( 'New Team Member', 'protaxllc' ),
		'view_item'                => esc_html__( 'View Team Member', 'protaxllc' ),
		'view_items'               => esc_html__( 'View Team Members', 'protaxllc' ),
		'search_items'             => esc_html__( 'Search Team Members', 'protaxllc' ),
		'not_found'                => esc_html__( 'No team members found.', 'protaxllc' ),
		'not_found_in_trash'       => esc_html__( 'No team members found in Trash.', 'protaxllc' ),
		'parent_item_colon'        => esc_html__( 'Parent Team Member:', 'protaxllc' ),
		'all_items'                => esc_html__( 'All Team Members', 'protaxllc' ),
		'archives'                 => esc_html__( 'Team Member Archives', 'protaxllc' ),
		'attributes'               => esc_html__( 'Team Member Attributes', 'protaxllc' ),
		'insert_into_item'         => esc_html__( 'Insert into team member', 'protaxllc' ),
		'uploaded_to_this_item'    => esc_html__( 'Uploaded to this team member', 'protaxllc' ),
		'featured_image'           => esc_html__( 'Featured image', 'protaxllc' ),
		'set_featured_image'       => esc_html__( 'Set featured image', 'protaxllc' ),
		'remove_featured_image'    => esc_html__( 'Remove featured image', 'protaxllc' ),
		'use_featured_image'       => esc_html__( 'Use as featured image', 'protaxllc' ),
		'menu_name'                => esc_html__( 'Team Members', 'protaxllc' ),
		'filter_items_list'        => esc_html__( 'Filter team members list', 'protaxllc' ),
		'filter_by_date'           => esc_html__( '', 'protaxllc' ),
		'items_list_navigation'    => esc_html__( 'Team Members list navigation', 'protaxllc' ),
		'items_list'               => esc_html__( 'Team Members list', 'protaxllc' ),
		'item_published'           => esc_html__( 'Team Member published.', 'protaxllc' ),
		'item_published_privately' => esc_html__( 'Team Member published privately.', 'protaxllc' ),
		'item_reverted_to_draft'   => esc_html__( 'Team Member reverted to draft.', 'protaxllc' ),
		'item_scheduled'           => esc_html__( 'Team Member scheduled.', 'protaxllc' ),
		'item_updated'             => esc_html__( 'Team Member updated.', 'protaxllc' ),
		'text_domain'              => esc_html__( 'protaxllc', 'protaxllc' ),
	];
	$args = [
		'label'               => esc_html__( 'Team Members', 'protaxllc' ),
		'labels'              => $labels,
		'description'         => 'Team Members',
		'public'              => true,
		'hierarchical'        => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'show_ui'             => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'show_in_rest'        => true,
		'query_var'           => true,
		'can_export'          => true,
		'delete_with_user'    => true,
		'order'               => true,
		'has_archive'         => false,
		'rest_base'           => '',
		'show_in_menu'        => true,
		'menu_position'       => '',
		'menu_icon'           => 'dashicons-businessman',
		'capability_type'     => 'page',
		'supports'            => ['title', 'editor', 'thumbnail', 'excerpt', 'revisions'],
		'taxonomies'          => [],
		'rewrite'             => [
			'with_front' => false,
		],
	];

	register_post_type( 'team-member', $args );
}