<?php
add_action( 'init', 'register_cs_types' );
function register_cs_types() {
	$labels = [
		'name'                       => esc_html__( 'Case Study Types', 'protax' ),
		'singular_name'              => esc_html__( 'Case Study Type', 'protax' ),
		'menu_name'                  => esc_html__( 'Types', 'protax' ),
		'all_items'                  => esc_html__( 'All Case Study Types', 'protax' ),
		'edit_item'                  => esc_html__( 'Edit Case Study Type', 'protax' ),
		'view_item'                  => esc_html__( 'View Case Study Type', 'protax' ),
		'update_item'                => esc_html__( 'Update Case Study Type', 'protax' ),
		'add_new_item'               => esc_html__( 'Add New Case Study Type', 'protax' ),
		'new_item_name'              => esc_html__( 'New Case Study Type Name', 'protax' ),
		'parent_item'                => esc_html__( 'Parent Case Study Type', 'protax' ),
		'parent_item_colon'          => esc_html__( 'Parent Case Study Type:', 'protax' ),
		'search_items'               => esc_html__( 'Search Case Study Types', 'protax' ),
		'most_used'                  => esc_html__( '', 'protax' ),
		'not_found'                  => esc_html__( 'No case study types found', 'protax' ),
		'no_terms'                   => esc_html__( 'No case study types', 'protax' ),
		'name_field_description'     => esc_html__( '', 'protax' ),
		'slug_field_description'     => esc_html__( '', 'protax' ),
		'parent_field_description'   => esc_html__( '', 'protax' ),
		'desc_field_description'     => esc_html__( '', 'protax' ),
		'filter_by_item'             => esc_html__( 'Filter by case study type', 'protax' ),
		'items_list_navigation'      => esc_html__( 'Case Study Types list navigation', 'protax' ),
		'items_list'                 => esc_html__( 'Case Study Types list', 'protax' ),
		'back_to_items'              => esc_html__( '← Go to case study types', 'protax' ),
		'item_link'                  => esc_html__( 'Case Study Type Link', 'protax' ),
		'item_link_description'      => esc_html__( 'A link to a case study type', 'protax' ),
		'popular_items'              => esc_html__( 'Popular Case Study Types', 'protax' ),
		'separate_items_with_commas' => esc_html__( 'Separate Case Study Types with commas', 'protax' ),
		'add_or_remove_items'        => esc_html__( 'Add or remove Case Study Types', 'protax' ),
		'choose_from_most_used'      => esc_html__( 'Choose from the most used Case Study Types', 'protax' ),
		'text_domain'                => esc_html__( 'protax', 'protax' ),
	];
	$args = [
		'label'                  => esc_html__( 'Case Study Types', 'protax' ),
		'labels'                 => $labels,
		'description'            => 'Case Study Type (Commercial, Residential, etc.)',
		'taxonomy'               => 'case-study-type',
		'object_type'            => 'case-study',
		'advanced_configuration' => 1,
		'import_source'          => '',
		'import_date'            => '',
		'capabilities'           => [object Object],
		'public'                 => 1,
		'publicly_queryable'     => 1,
		'hierarchical'           => true,
		'show_ui'                => 1,
		'show_in_menu'           => 1,
		'show_in_nav_menus'      => 1,
		'show_in_rest'           => 1,
		'rest_namespace'         => wp/v2,
		'rest_controller_class'  => WP_REST_Terms_Controller,
		'show_tagcloud'          => 0,
		'show_in_quick_edit'     => 1,
		'show_admin_column'      => 1,
		'query_var'              => true,
		'query_var_name'         => '',
		'default_term'           => [object Object],
		'sort'                   => 1,
		'meta_box'               => default,
		'meta_box_sanitize_cb'   => '',
		'meta_box_cb'            => 'post_categories_meta_box',
		'rest_base'              => '',
		'rewrite'                => [
			'with_front'   => true,
			'hierarchical' => true,
		],
	];
	register_taxonomy( 'case-study-type', ['case_study', 'case-study'], $args );
}

add_action( 'init', 'register_cs_timeline' );
function register_cs_timeline() {
	$labels = [
		'name'                       => esc_html__( 'Case Study Timelines', 'protax' ),
		'singular_name'              => esc_html__( 'Case Study Timeline', 'protax' ),
		'menu_name'                  => esc_html__( 'Timelines', 'protax' ),
		'all_items'                  => esc_html__( 'All Case Study Timelines', 'protax' ),
		'edit_item'                  => esc_html__( 'Edit Case Study Timeline', 'protax' ),
		'view_item'                  => esc_html__( 'View Case Study Timeline', 'protax' ),
		'update_item'                => esc_html__( 'Update Case Study Timeline', 'protax' ),
		'add_new_item'               => esc_html__( 'Add New Case Study Timeline', 'protax' ),
		'new_item_name'              => esc_html__( 'New Case Study Timeline Name', 'protax' ),
		'parent_item'                => esc_html__( 'Parent Case Study Timeline', 'protax' ),
		'parent_item_colon'          => esc_html__( 'Parent Case Study Timeline:', 'protax' ),
		'search_items'               => esc_html__( 'Search Case Study Timelines', 'protax' ),
		'most_used'                  => esc_html__( '', 'protax' ),
		'not_found'                  => esc_html__( 'No case study timelines found', 'protax' ),
		'no_terms'                   => esc_html__( 'No case study timelines', 'protax' ),
		'name_field_description'     => esc_html__( '', 'protax' ),
		'slug_field_description'     => esc_html__( '', 'protax' ),
		'parent_field_description'   => esc_html__( '', 'protax' ),
		'desc_field_description'     => esc_html__( '', 'protax' ),
		'filter_by_item'             => esc_html__( 'Filter by case study timeline', 'protax' ),
		'items_list_navigation'      => esc_html__( 'Case Study Timelines list navigation', 'protax' ),
		'items_list'                 => esc_html__( 'Case Study Timelines list', 'protax' ),
		'back_to_items'              => esc_html__( '← Go to case study timelines', 'protax' ),
		'item_link'                  => esc_html__( 'Case Study Timeline Link', 'protax' ),
		'item_link_description'      => esc_html__( 'A link to a case study timeline', 'protax' ),
		'popular_items'              => esc_html__( 'Popular Case Study Timelines', 'protax' ),
		'separate_items_with_commas' => esc_html__( 'Separate Case Study Timelines with commas', 'protax' ),
		'add_or_remove_items'        => esc_html__( 'Add or remove Case Study Timelines', 'protax' ),
		'choose_from_most_used'      => esc_html__( 'Choose from the most used Case Study Timelines', 'protax' ),
		'text_domain'                => esc_html__( 'protax', 'protax' ),
	];
	$args = [
		'label'                  => esc_html__( 'Case Study Timelines', 'protax' ),
		'labels'                 => $labels,
		'description'            => 'Case Study Timeline in Decades',
		'taxonomy'               => 'case-study-timeline',
		'object_type'            => case_study,
		'advanced_configuration' => 1,
		'import_source'          => '',
		'import_date'            => '',
		'capabilities'           => [object Object],
		'public'                 => 1,
		'publicly_queryable'     => 1,
		'hierarchical'           => true,
		'show_ui'                => 1,
		'show_in_menu'           => 1,
		'show_in_nav_menus'      => 1,
		'show_in_rest'           => 1,
		'rest_namespace'         => wp/v2,
		'rest_controller_class'  => WP_REST_Terms_Controller,
		'show_tagcloud'          => 0,
		'show_in_quick_edit'     => 1,
		'show_admin_column'      => 1,
		'query_var'              => true,
		'query_var_name'         => '',
		'default_term'           => [object Object],
		'sort'                   => 1,
		'meta_box'               => default,
		'meta_box_sanitize_cb'   => '',
		'meta_box_cb'            => 'post_categories_meta_box',
		'rest_base'              => '',
		'rewrite'                => [
			'with_front'   => true,
			'hierarchical' => true,
		],
	];
	register_taxonomy( 'case-study-timeline', ['case_study', 'case-study'], $args );
}

add_action( 'init', 'register_cs_counties' );
function register_cs_counties() {
	$labels = [
		'name'                       => esc_html__( 'Case Study Counties', 'protax' ),
		'singular_name'              => esc_html__( 'Case Study County', 'protax' ),
		'menu_name'                  => esc_html__( 'Counties', 'protax' ),
		'all_items'                  => esc_html__( 'All Case Study Counties', 'protax' ),
		'edit_item'                  => esc_html__( 'Edit Case Study County', 'protax' ),
		'view_item'                  => esc_html__( 'View Case Study County', 'protax' ),
		'update_item'                => esc_html__( 'Update Case Study County', 'protax' ),
		'add_new_item'               => esc_html__( 'Add New Case Study County', 'protax' ),
		'new_item_name'              => esc_html__( 'New Case Study County Name', 'protax' ),
		'parent_item'                => esc_html__( 'Parent Case Study County', 'protax' ),
		'parent_item_colon'          => esc_html__( 'Parent Case Study County:', 'protax' ),
		'search_items'               => esc_html__( 'Search Case Study Counties', 'protax' ),
		'most_used'                  => esc_html__( '', 'protax' ),
		'not_found'                  => esc_html__( 'No case study counties found', 'protax' ),
		'no_terms'                   => esc_html__( 'No case study counties', 'protax' ),
		'name_field_description'     => esc_html__( '', 'protax' ),
		'slug_field_description'     => esc_html__( '', 'protax' ),
		'parent_field_description'   => esc_html__( '', 'protax' ),
		'desc_field_description'     => esc_html__( '', 'protax' ),
		'filter_by_item'             => esc_html__( 'Filter by case study county', 'protax' ),
		'items_list_navigation'      => esc_html__( 'Case Study Counties list navigation', 'protax' ),
		'items_list'                 => esc_html__( 'Case Study Counties list', 'protax' ),
		'back_to_items'              => esc_html__( '← Go to case study counties', 'protax' ),
		'item_link'                  => esc_html__( 'Case Study County Link', 'protax' ),
		'item_link_description'      => esc_html__( 'A link to a case study county', 'protax' ),
		'popular_items'              => esc_html__( 'Popular Case Study Counties', 'protax' ),
		'separate_items_with_commas' => esc_html__( 'Separate Case Study Counties with commas', 'protax' ),
		'add_or_remove_items'        => esc_html__( 'Add or remove Case Study Counties', 'protax' ),
		'choose_from_most_used'      => esc_html__( 'Choose from the most used Case Study Counties', 'protax' ),
		'text_domain'                => esc_html__( 'protax', 'protax' ),
	];
	$args = [
		'label'                  => esc_html__( 'Case Study Counties', 'protax' ),
		'labels'                 => $labels,
		'description'            => 'The County related to the Case Study',
		'taxonomy'               => 'case-study-county',
		'object_type'            => case_study,
		'advanced_configuration' => 1,
		'import_source'          => '',
		'import_date'            => '',
		'capabilities'           => [object Object],
		'public'                 => 1,
		'publicly_queryable'     => 1,
		'hierarchical'           => false,
		'show_ui'                => 1,
		'show_in_menu'           => 1,
		'show_in_nav_menus'      => 1,
		'show_in_rest'           => 1,
		'rest_namespace'         => wp/v2,
		'rest_controller_class'  => WP_REST_Terms_Controller,
		'show_tagcloud'          => 0,
		'show_in_quick_edit'     => 1,
		'show_admin_column'      => 1,
		'query_var'              => true,
		'query_var_name'         => '',
		'default_term'           => [object Object],
		'sort'                   => 1,
		'meta_box'               => default,
		'meta_box_sanitize_cb'   => '',
		'meta_box_cb'            => 'post_tags_meta_box',
		'rest_base'              => '',
		'rewrite'                => [
			'with_front'   => false,
			'hierarchical' => false,
		],
	];
	register_taxonomy( 'case-study-county', ['case_study', 'case-study'], $args );
}